#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'build-essential'

cookbook 'python'

cookbook 'buildgap-shell',
  :git => 'https://github.com/indoorsdog/buildgap',
  :path => 'chef/cookbooks/buildgap-shell'

cookbook 'node'

cookbook 'rbenv'

cookbook 'java',
  :git => 'https://github.com/indoorsdog/fork_opscode-cookbooks_java'

cookbook 'gradle',
  :git => 'https://github.com/indoorsdog/fork_michaelklishin_gradle-chef-cookbook'

cookbook 'perlbrew'