#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'build-essential'

cookbook 'python'

cookbook 'git'

cookbook 'nodejs'

cookbook 'rbenv'

cookbook 'java',
  :git => 'https://github.com/indoorsdog/_fork_opscode-cookbooks_java'

cookbook 'gradle',
  :git => 'https://github.com/indoorsdog/_fork_michaelklishin_gradle-chef-cookbook'

cookbook 'perlbrew'